### ISSUE TITLE
翻訳希望 12章

### ISSUE THREAD

**Issue by milktea-muffin** [resnant/dmol-book-japanese#10]
# 翻訳希望する章
12章

# おおよそのスケジュール
8月中

# クレジットの表記
まだ決めかねていますので、プルリク時までお待ちいただけますでしょうか。

**Comment by resnant** [comment]
ありがとうございます！よろしくお願いします。
クレジットについても了解しました。

**Comment by milktea-muffin** [comment]
ご連絡が遅くなり申し訳ありません。9月末頃まで延長させていただけますでしょうか。

**Comment by resnant** [comment]
はい、もちろん大丈夫です 👌🏻
ご不明な点などあればお気軽にご相談ください
