### ISSUE TITLE
翻訳希望 13章

### ISSUE THREAD

**Issue by sunbluesome** [resnant/dmol-book-japanese#11]
# 翻訳希望する章
13章（[Attention Layers](https://resnant.github.io/dmol-book-japanese/dl/attention.html)）

# おおよそのスケジュール
8月中~9月上旬

# クレジットの表記
Haruki Inoue [@sunbluesome](https://twitter.com/sunbluesome)

**Comment by resnant** [comment]
ありがとうございます！よろしくお願いします👍🏻

**Comment by sunbluesome** [comment]
@resnant 
申し訳ないのですが、もう少々お時間下さい。
9月中に仕上げる目標です。

**Comment by resnant** [comment]
了解しました！
特に締切があるわけはないのでご無理ない範囲で進めていただければ幸いです。
ご不明な点があればお気軽にご相談ください

**Comment by sunbluesome** [comment]
9月を過ぎて決まったので、念のためのご報告です。

最近業務過多でこちらの進捗が滞っていますが、およそ2/3程度までは完了しています。

もう少しかかりますが、しばしお待ちください。

**Comment by resnant** [comment]
ご連絡ありがとうございます。状況了解です！
ご無理ない範囲で進めていただければ幸いです
