### ISSUE TITLE
翻訳希望 2章 

### ISSUE THREAD

**Issue by Ikwus** [resnant/dmol-book-japanese#4]
# 翻訳希望する章
2. introduction (Machine-Learning)

# おおよそのスケジュール
~7/16

# クレジットの表記
Issei Tomotsuka (@mt03kkk18wu)

**Comment by Ikwus** [comment]
#2 でとりあえず翻訳終了。
@resnant 
よく使う単語は対訳リストを作って用語を作ったほうがいいですかね？

**Comment by resnant** [comment]
対訳リスト作ると翻訳の負担上がりそうなので、まずはリスト作らず多少の表記ゆれは気にせず進めて、全部訳し終わったら校正していくのがいいのかなと思ってます（他に手伝ってくれる人いるかもしれないので、最初のハードルは低めにしておきたい）。もちろん個人的に作って使ってもらう分にはOKです！

**Comment by resnant** [comment]
既に翻訳作業終わってるかと思うので一旦クローズします 🙏🏻 もし必要であれば再オープンお願いします
