### ISSUE TITLE
翻訳希望 5章

### ISSUE THREAD

**Issue by Riku-KANO** [resnant/dmol-book-japanese#9]
# 翻訳希望する章
5章（Kernel Learning）

# おおよそのスケジュール
8/20

# クレジットの表記
希望なし

**Comment by resnant** [comment]
ありがとうございます！よろしくお願いします。わからない点などあればお気軽にお問い合わせください。
クレジット表記の希望なしということですが、各章のcontributorを記載する際には「@Riku-KANO さん」という記載でよろしいでしょうか？

**Comment by Riku-KANO** [comment]
期日通りに進められるかはわかりませんが、よろしくお願い致します。
はい、contributorの記載は「@Riku-KANO さん」でも構いません。
